/**
 *
 *  Favorregions.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Favorregions.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::travelapp;

const std::string Favorregions::Cols::_uname = "uname";
const std::string Favorregions::Cols::_rid = "rid";
const std::vector<std::string> Favorregions::primaryKeyName = {"uname","rid"};
const bool Favorregions::hasPrimaryKey = true;
const std::string Favorregions::tableName = "favorregions";

const std::vector<typename Favorregions::MetaData> Favorregions::metaData_={
{"uname","std::string","character varying",255,0,1,1},
{"rid","int32_t","integer",4,0,1,1}
};
const std::string &Favorregions::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Favorregions::Favorregions(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["uname"].isNull())
        {
            uname_=std::make_shared<std::string>(r["uname"].as<std::string>());
        }
        if(!r["rid"].isNull())
        {
            rid_=std::make_shared<int32_t>(r["rid"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            uname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            rid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Favorregions::Favorregions(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uname_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

Favorregions::Favorregions(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uname"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["uname"].isNull())
        {
            uname_=std::make_shared<std::string>(pJson["uname"].asString());
        }
    }
    if(pJson.isMember("rid"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["rid"].isNull())
        {
            rid_=std::make_shared<int32_t>((int32_t)pJson["rid"].asInt64());
        }
    }
}

void Favorregions::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uname_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void Favorregions::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uname"))
    {
        if(!pJson["uname"].isNull())
        {
            uname_=std::make_shared<std::string>(pJson["uname"].asString());
        }
    }
    if(pJson.isMember("rid"))
    {
        if(!pJson["rid"].isNull())
        {
            rid_=std::make_shared<int32_t>((int32_t)pJson["rid"].asInt64());
        }
    }
}

const std::string &Favorregions::getValueOfUname() const noexcept
{
    const static std::string defaultValue = std::string();
    if(uname_)
        return *uname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Favorregions::getUname() const noexcept
{
    return uname_;
}
void Favorregions::setUname(const std::string &pUname) noexcept
{
    uname_ = std::make_shared<std::string>(pUname);
    dirtyFlag_[0] = true;
}
void Favorregions::setUname(std::string &&pUname) noexcept
{
    uname_ = std::make_shared<std::string>(std::move(pUname));
    dirtyFlag_[0] = true;
}

const int32_t &Favorregions::getValueOfRid() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(rid_)
        return *rid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Favorregions::getRid() const noexcept
{
    return rid_;
}
void Favorregions::setRid(const int32_t &pRid) noexcept
{
    rid_ = std::make_shared<int32_t>(pRid);
    dirtyFlag_[1] = true;
}

void Favorregions::updateId(const uint64_t id)
{
}
typename Favorregions::PrimaryKeyType Favorregions::getPrimaryKey() const
{
    return std::make_tuple(*uname_,*rid_);
}

const std::vector<std::string> &Favorregions::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uname",
        "rid"
    };
    return inCols;
}

void Favorregions::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUname())
        {
            binder << getValueOfUname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRid())
        {
            binder << getValueOfRid();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Favorregions::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Favorregions::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUname())
        {
            binder << getValueOfUname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRid())
        {
            binder << getValueOfRid();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Favorregions::toJson() const
{
    Json::Value ret;
    if(getUname())
    {
        ret["uname"]=getValueOfUname();
    }
    else
    {
        ret["uname"]=Json::Value();
    }
    if(getRid())
    {
        ret["rid"]=getValueOfRid();
    }
    else
    {
        ret["rid"]=Json::Value();
    }
    return ret;
}

Json::Value Favorregions::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUname())
            {
                ret[pMasqueradingVector[0]]=getValueOfUname();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRid())
            {
                ret[pMasqueradingVector[1]]=getValueOfRid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUname())
    {
        ret["uname"]=getValueOfUname();
    }
    else
    {
        ret["uname"]=Json::Value();
    }
    if(getRid())
    {
        ret["rid"]=getValueOfRid();
    }
    else
    {
        ret["rid"]=Json::Value();
    }
    return ret;
}

bool Favorregions::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uname"))
    {
        if(!validJsonOfField(0, "uname", pJson["uname"], err, true))
            return false;
    }
    else
    {
        err="The uname column cannot be null";
        return false;
    }
    if(pJson.isMember("rid"))
    {
        if(!validJsonOfField(1, "rid", pJson["rid"], err, true))
            return false;
    }
    else
    {
        err="The rid column cannot be null";
        return false;
    }
    return true;
}
bool Favorregions::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Favorregions::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uname"))
    {
        if(!validJsonOfField(0, "uname", pJson["uname"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("rid"))
    {
        if(!validJsonOfField(1, "rid", pJson["rid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool Favorregions::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Favorregions::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
