/**
 *
 *  Favquestion.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Favquestion.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::travelapp;

const std::string Favquestion::Cols::_uid = "uid";
const std::string Favquestion::Cols::_qid = "qid";
const std::vector<std::string> Favquestion::primaryKeyName = {"uid","qid"};
const bool Favquestion::hasPrimaryKey = true;
const std::string Favquestion::tableName = "favquestion";

const std::vector<typename Favquestion::MetaData> Favquestion::metaData_={
{"uid","int32_t","integer",4,0,1,1},
{"qid","int32_t","integer",4,0,1,1}
};
const std::string &Favquestion::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Favquestion::Favquestion(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["uid"].isNull())
        {
            uid_=std::make_shared<int32_t>(r["uid"].as<int32_t>());
        }
        if(!r["qid"].isNull())
        {
            qid_=std::make_shared<int32_t>(r["qid"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            uid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            qid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Favquestion::Favquestion(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            qid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

Favquestion::Favquestion(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uid"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["uid"].isNull())
        {
            uid_=std::make_shared<int32_t>((int32_t)pJson["uid"].asInt64());
        }
    }
    if(pJson.isMember("qid"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["qid"].isNull())
        {
            qid_=std::make_shared<int32_t>((int32_t)pJson["qid"].asInt64());
        }
    }
}

void Favquestion::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            qid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void Favquestion::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uid"))
    {
        if(!pJson["uid"].isNull())
        {
            uid_=std::make_shared<int32_t>((int32_t)pJson["uid"].asInt64());
        }
    }
    if(pJson.isMember("qid"))
    {
        if(!pJson["qid"].isNull())
        {
            qid_=std::make_shared<int32_t>((int32_t)pJson["qid"].asInt64());
        }
    }
}

const int32_t &Favquestion::getValueOfUid() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(uid_)
        return *uid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Favquestion::getUid() const noexcept
{
    return uid_;
}
void Favquestion::setUid(const int32_t &pUid) noexcept
{
    uid_ = std::make_shared<int32_t>(pUid);
    dirtyFlag_[0] = true;
}

const int32_t &Favquestion::getValueOfQid() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(qid_)
        return *qid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Favquestion::getQid() const noexcept
{
    return qid_;
}
void Favquestion::setQid(const int32_t &pQid) noexcept
{
    qid_ = std::make_shared<int32_t>(pQid);
    dirtyFlag_[1] = true;
}

void Favquestion::updateId(const uint64_t id)
{
}
typename Favquestion::PrimaryKeyType Favquestion::getPrimaryKey() const
{
    return std::make_tuple(*uid_,*qid_);
}

const std::vector<std::string> &Favquestion::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uid",
        "qid"
    };
    return inCols;
}

void Favquestion::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUid())
        {
            binder << getValueOfUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getQid())
        {
            binder << getValueOfQid();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Favquestion::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Favquestion::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUid())
        {
            binder << getValueOfUid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getQid())
        {
            binder << getValueOfQid();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Favquestion::toJson() const
{
    Json::Value ret;
    if(getUid())
    {
        ret["uid"]=getValueOfUid();
    }
    else
    {
        ret["uid"]=Json::Value();
    }
    if(getQid())
    {
        ret["qid"]=getValueOfQid();
    }
    else
    {
        ret["qid"]=Json::Value();
    }
    return ret;
}

Json::Value Favquestion::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUid())
            {
                ret[pMasqueradingVector[0]]=getValueOfUid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getQid())
            {
                ret[pMasqueradingVector[1]]=getValueOfQid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUid())
    {
        ret["uid"]=getValueOfUid();
    }
    else
    {
        ret["uid"]=Json::Value();
    }
    if(getQid())
    {
        ret["qid"]=getValueOfQid();
    }
    else
    {
        ret["qid"]=Json::Value();
    }
    return ret;
}

bool Favquestion::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uid"))
    {
        if(!validJsonOfField(0, "uid", pJson["uid"], err, true))
            return false;
    }
    else
    {
        err="The uid column cannot be null";
        return false;
    }
    if(pJson.isMember("qid"))
    {
        if(!validJsonOfField(1, "qid", pJson["qid"], err, true))
            return false;
    }
    else
    {
        err="The qid column cannot be null";
        return false;
    }
    return true;
}
bool Favquestion::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Favquestion::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uid"))
    {
        if(!validJsonOfField(0, "uid", pJson["uid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("qid"))
    {
        if(!validJsonOfField(1, "qid", pJson["qid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool Favquestion::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Favquestion::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
