/**
 *
 *  Traveler.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Traveler.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::travelapp;

const std::string Traveler::Cols::_uname = "uname";
const std::string Traveler::Cols::_pwd = "pwd";
const std::string Traveler::primaryKeyName = "uname";
const bool Traveler::hasPrimaryKey = true;
const std::string Traveler::tableName = "traveler";

const std::vector<typename Traveler::MetaData> Traveler::metaData_={
{"uname","std::string","character varying",255,0,1,1},
{"pwd","std::string","character varying",255,0,0,1}
};
const std::string &Traveler::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Traveler::Traveler(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["uname"].isNull())
        {
            uname_=std::make_shared<std::string>(r["uname"].as<std::string>());
        }
        if(!r["pwd"].isNull())
        {
            pwd_=std::make_shared<std::string>(r["pwd"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            uname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            pwd_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Traveler::Traveler(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uname_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            pwd_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Traveler::Traveler(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uname"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["uname"].isNull())
        {
            uname_=std::make_shared<std::string>(pJson["uname"].asString());
        }
    }
    if(pJson.isMember("pwd"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["pwd"].isNull())
        {
            pwd_=std::make_shared<std::string>(pJson["pwd"].asString());
        }
    }
}

void Traveler::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            uname_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            pwd_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Traveler::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("uname"))
    {
        if(!pJson["uname"].isNull())
        {
            uname_=std::make_shared<std::string>(pJson["uname"].asString());
        }
    }
    if(pJson.isMember("pwd"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["pwd"].isNull())
        {
            pwd_=std::make_shared<std::string>(pJson["pwd"].asString());
        }
    }
}

const std::string &Traveler::getValueOfUname() const noexcept
{
    const static std::string defaultValue = std::string();
    if(uname_)
        return *uname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Traveler::getUname() const noexcept
{
    return uname_;
}
void Traveler::setUname(const std::string &pUname) noexcept
{
    uname_ = std::make_shared<std::string>(pUname);
    dirtyFlag_[0] = true;
}
void Traveler::setUname(std::string &&pUname) noexcept
{
    uname_ = std::make_shared<std::string>(std::move(pUname));
    dirtyFlag_[0] = true;
}
const typename Traveler::PrimaryKeyType & Traveler::getPrimaryKey() const
{
    assert(uname_);
    return *uname_;
}

const std::string &Traveler::getValueOfPwd() const noexcept
{
    const static std::string defaultValue = std::string();
    if(pwd_)
        return *pwd_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Traveler::getPwd() const noexcept
{
    return pwd_;
}
void Traveler::setPwd(const std::string &pPwd) noexcept
{
    pwd_ = std::make_shared<std::string>(pPwd);
    dirtyFlag_[1] = true;
}
void Traveler::setPwd(std::string &&pPwd) noexcept
{
    pwd_ = std::make_shared<std::string>(std::move(pPwd));
    dirtyFlag_[1] = true;
}

void Traveler::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Traveler::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "uname",
        "pwd"
    };
    return inCols;
}

void Traveler::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUname())
        {
            binder << getValueOfUname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPwd())
        {
            binder << getValueOfPwd();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Traveler::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Traveler::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUname())
        {
            binder << getValueOfUname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getPwd())
        {
            binder << getValueOfPwd();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Traveler::toJson() const
{
    Json::Value ret;
    if(getUname())
    {
        ret["uname"]=getValueOfUname();
    }
    else
    {
        ret["uname"]=Json::Value();
    }
    if(getPwd())
    {
        ret["pwd"]=getValueOfPwd();
    }
    else
    {
        ret["pwd"]=Json::Value();
    }
    return ret;
}

Json::Value Traveler::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUname())
            {
                ret[pMasqueradingVector[0]]=getValueOfUname();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPwd())
            {
                ret[pMasqueradingVector[1]]=getValueOfPwd();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUname())
    {
        ret["uname"]=getValueOfUname();
    }
    else
    {
        ret["uname"]=Json::Value();
    }
    if(getPwd())
    {
        ret["pwd"]=getValueOfPwd();
    }
    else
    {
        ret["pwd"]=Json::Value();
    }
    return ret;
}

bool Traveler::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uname"))
    {
        if(!validJsonOfField(0, "uname", pJson["uname"], err, true))
            return false;
    }
    else
    {
        err="The uname column cannot be null";
        return false;
    }
    if(pJson.isMember("pwd"))
    {
        if(!validJsonOfField(1, "pwd", pJson["pwd"], err, true))
            return false;
    }
    else
    {
        err="The pwd column cannot be null";
        return false;
    }
    return true;
}
bool Traveler::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Traveler::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("uname"))
    {
        if(!validJsonOfField(0, "uname", pJson["uname"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("pwd"))
    {
        if(!validJsonOfField(1, "pwd", pJson["pwd"], err, false))
            return false;
    }
    return true;
}
bool Traveler::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Traveler::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
